In [1]:
import pandas as pd
data = pd.read_csv("New_IOT_Data.csv", encoding= 'unicode_escape')

In [2]:
# import required libraries
from sklearn.ensemble import ExtraTreesRegressor
import numpy as np

# create some random data for demonstration
X = np.array(data[['Total CPU Usage [%]' , 'CPU SOC [°C]']])
y = np.array(data['Core+SoC Power (SVI2 TFN) [W]'])

# create an instance of the Extra Trees Regressor
regressor = ExtraTreesRegressor(n_estimators=100, random_state=0)

In [3]:
# fit the regressor to the data
regressor.fit(X, y)

# predict the target variable for some new input data
new_data = np.array([[0.2, 0.3], [0.4, 0.5]])
predictions = regressor.predict(new_data)

# print the predicted values
print(predictions)

[2.47615 2.405  ]

In [4]:
y_pred = regressor.predict(X)

In [5]:
from sklearn.metrics import r2_score, mean_squared_error


# calculate the R-squared score
r2 = r2_score(y, y_pred)
print("R-squared score:", r2)

# calculate the mean squared error
mse = mean_squared_error(y, y_pred)
print("Mean squared error:", mse)

R-squared score: 0.9884785121512061
Mean squared error: 0.7091750114648777

In [6]:
from sklearn.metrics import r2_score, mean_squared_error

# assuming you have y_actual and y_predicted as numpy arrays
y_actual = y
y_predicted = y_pred

# calculate the R-squared score
r2 = r2_score(y_actual, y_predicted)
r2_percentage = r2 * 100
print("R-squared score:", r2_percentage, "%")

# calculate the mean squared error
mse = mean_squared_error(y_actual, y_predicted)
mse_percentage = mse * 100
print("Mean squared error:", mse_percentage, "%")

R-squared score: 98.84785121512061 %
Mean squared error: 70.91750114648777 %

In [7]:
import pickle
pickle.dump(regressor, open('model_regressor.pkl', 'wb'))

In [8]:
pickled_model = pickle.load(open('model_regressor.pkl', 'rb'))
pickled_model.predict(X)

array([ 8.51      , 12.887     ,  9.528     , ...,  8.87166667,
        8.87166667, 13.0805    ])

In [9]:
data

,Date,Time,Time.1,Total CPU Usage [%],CPU SOC [°C],Core+SoC Power (SVI2 TFN) [W],GPU Memory Usage [%],GPU Temperature [°C],GPU Power [W],Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,29.12.2022,0:30:10,30:11.0,2.1,50.5,8.510,5.1,42.8,3.258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,29.12.2022,0:30:13,12:30:13,2.3,51.6,12.887,5.1,43.2,3.416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29.12.2022,0:30:15,12:30:15,1.7,51.0,9.528,5.1,43.1,3.313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29.12.2022,0:30:17,12:30:17,6.4,53.3,18.423,5.1,43.2,2.977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,29.12.2022,0:30:19,12:30:19,4.2,53.5,14.836,5.1,43.5,3.064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37831,29.12.2022,0:12:23,9:31:13,1.8,48.3,5.074,5.8,42.4,3.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37832,29.12.2022,0:12:25,9:31:15,1.8,48.3,4.940,5.8,42.5,2.994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37833,29.12.2022,0:12:27,9:31:17,1.9,48.6,5.979,5.8,42.6,2.973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37834,29.12.2022,0:12:29,9:31:19,1.9,48.6,5.979,5.8,42.6,2.973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37835,29.12.2022,0:12:29,9:31:21,5.1,50.1,12.467,5.8,42.6,2.853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# import required libraries
from sklearn.ensemble import ExtraTreesRegressor
import numpy as np

# create some random data for demonstration
X = np.array(data[['GPU Memory Usage [%]' , 'GPU Temperature [°C]']])
y = np.array(data['GPU Power [W]'])

# create an instance of the Extra Trees Regressor
regressor = ExtraTreesRegressor(n_estimators=100, random_state=0)

In [11]:
# fit the regressor to the data
regressor.fit(X, y)

# predict the target variable for some new input data
new_data = np.array([[0.2, 0.3], [0.4, 0.5]])
predictions = regressor.predict(new_data)

# print the predicted values
print(predictions)

[2.77858 2.77858]

In [12]:
y_pred = regressor.predict(X)

In [13]:
import pickle
pickle.dump(regressor, open('model_regressor_gpu.pkl', 'wb'))